# Generated by Django 5.2.15 on 2026-06-10 16:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS Truckstop ID from the CSV dataset')),
                ('name', models.CharField(help_text="Truck stop name (e.g., 'PILOT TRAVEL CENTER #1243')", max_length=255)),
                ('address', models.CharField(help_text='Street address or interstate exit info', max_length=255)),
                ('city', models.CharField(help_text='City name', max_length=100)),
                ('state', models.CharField(help_text="State abbreviation (e.g., 'TX', 'CA')", max_length=10)),
                ('rack_id', models.IntegerField(help_text='Rack ID from the pricing data')),
                ('retail_price', models.FloatField(db_index=True, help_text='Retail fuel price in dollars per gallon')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geocoded GPS coordinates (longitude, latitude)', null=True, srid=4326)),
                ('latitude', models.FloatField(blank=True, db_index=True, help_text='Latitude in decimal degrees', null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, help_text='Longitude in decimal degrees', null=True)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'ordering': ['retail_price'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_lat_lng')],
            },
        ),
    ]
